//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImobFeed.Core.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringContent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringContent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImobFeed.Core.Tests.StringContent", typeof(StringContent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ultimaAtualizacao&quot;:&quot;2022-09-14T00:10:02.8125943+00:00&quot;,&quot;ativos&quot;:[{&quot;codigo&quot;:&quot;ABCP11&quot;,&quot;nome&quot;:&quot;Grand Plaza Shopping&quot;,&quot;valorCota&quot;:75.66,&quot;dataCotacao&quot;:&quot;2022-09-13T17:05:00-03:00&quot;,&quot;dataIpo&quot;:&quot;2004-03-12&quot;,&quot;valorIpo&quot;:18.50,&quot;segmento&quot;:&quot;Shopping/Varejo&quot;,&quot;administrador&quot;:&quot;RIO BRAVO&quot;},{&quot;codigo&quot;:&quot;AFHI11&quot;,&quot;nome&quot;:&quot;AF Invest CRI&quot;,&quot;valorCota&quot;:101.10,&quot;dataCotacao&quot;:&quot;2022-09-13T17:05:00-03:00&quot;,&quot;dataIpo&quot;:&quot;2021-04-05&quot;,&quot;valorIpo&quot;:100.00,&quot;segmento&quot;:&quot;Receb\u00EDveis Imobili\u00E1rios&quot;,&quot;administrador&quot;:&quot;BTG PACTUAL&quot;},{&quot;codigo&quot;:&quot;AGRX1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListaAtivosJson {
            get {
                return ResourceManager.GetString("ListaAtivosJson", resourceCulture);
            }
        }
    }
}
